backend:
  name: github
  repo: jbcima/chorus
  branch: main

site_url: https://or-us.ch/

logo_url: /images/logo.png

media_folder: "static/uploads" 
public_folder: "/uploads"

collections:
  - name: pages
    label: Pages
    label_singular: 'Page'
    folder: content/pages
    create: true
    nested:
      depth: 100 
    fields:
      - label: Title
        name: title
        widget: string
      - label: Body
        required: false
        name: body
        widget: markdown
      - label: "Audio"
        required: false
        name: "audio"
        widget: "file"
        media_library:
          config:
            multiple: true
    meta: { path: { widget: string, label: 'Path', index_file: 'index' } }