backend:
  name: github

logo_url: /images/logo.png

media_folder: "static/uploads" 
public_folder: "/uploads"

editor:
  preview: false

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/s"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: pages
    label: Pages
    label_singular: 'Page'
    folder: src/pages/_pages
    create: true
    nested:
      depth: 100 
    fields:
      - label: Title
        name: title
        widget: string
      - label: Description
        required: false
        name: description
        widget: string
      - label: 'Content'
        name: 'content'
        widget: 'list'
        types:
          - label: 'Track'
            name: 'track'
            widget: 'object'
            fields:
              - {label: Artist, name: artist, widget: string, required: false}
              - {label: Title, name: title, widget: string }
              - {label: File, name: file, widget: string}
              - {label: Art, name: art, widget: "file", required: false}
          - label: 'Album'
            name: 'album'
            widget: 'object'
            fields:
            - label: Artist
              name: artist
              required: false
              widget: string
            - label: Title
              name: title
              required: false
              widget: string
            - label: Art
              name: art
              required: false
              widget: "file"
            - label: 'Track'
              name: 'track'
              widget: 'list'
              fields:
                - {label: Artist, name: artist, widget: string, required: false}
                - {label: Title, name: title, widget: string }
                - {label: File, name: file, widget: string}
                - {label: Art, name: art, widget: "file", required: false}
    meta: { path: { widget: string, label: 'Path', index_file: 'index' } }